Merge master changes into v2.1.0 branch
wso2/puppet-apim pull request #33
Opened 2017-06-18 07:04 UTC by rmsamitha

2017-06-18 17:20 UTC, prasa7 requested changes

2017-06-18 17:20 UTC, prasa7 commented on wso2am_runtime/README.md
> +- Puppet 3.x
Have we tested our patterns with Puppet 3 ?

2017-06-18 18:28 UTC, rmsamitha commented on wso2am_runtime/README.md
> +- Puppet 3.x
Yes, the version we tested is Puppet 3

2017-06-19 11:23 UTC, anuruddhal approved these changes

2017-06-19 13:34 UTC, rmsamitha commented on wso2am_runtime/README.md
> +- Puppet 3.x
@prasa7 Could you please update the review as approved since no changes are required for this and this blocks merging pull/31

2017-06-20 04:25 UTC, prasa7 approved these changes

2017-06-20 04:27 UTC, merged